# Generated by Django 5.1.6 on 2025-03-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_testimonial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_phone_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
